In [23]:
# Import Pandas library
import pandas as pd

In [24]:
# Create employee dataset
employees = {
    "Name": ["Garima", "Jasmine", "Amit", "Reyansh", "Missi", "Shaurya", "Zayn"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Finance", "HR"],
    "Salary": [30000, 50000, 45000, 60000, 25000, 90000, 35000]
}

# Convert the employee dataset into a Pandas DataFrame
df = pd.DataFrame(employees)

print("Employee dataset:")
df

Employee dataset:

      Name Department  Salary
0   Garima         HR   30000
1  Jasmine         IT   50000
2     Amit    Finance   45000
3  Reyansh         IT   60000
4    Missi         HR   25000
5  Shaurya    Finance   90000
6     Zayn         HR   35000

In [31]:
# 1. Calculate average salary department-wise

# Use groupby() and mean() to calculate the average salary for each department
average_salary = df.groupby("Department")["Salary"].mean().reset_index(name="Average Salary")

print("Average salary for each department:")
average_salary

Average salary for each department:

  Department  Average Salary
0    Finance         67500.0
1         HR         30000.0
2         IT         55000.0

In [32]:
# 2. Find max salary by department

# Use groupby() and max() to find the highest salary in each department
max_salary = df.groupby("Department") ["Salary"].max().reset_index(name="Maximum Salary")

print("Highest salary in each department:")
max_salary

Highest salary in each department:

  Department  Maximum Salary
0    Finance           90000
1         HR           35000
2         IT           60000

In [33]:
# 3. Count employees in each department

# Use groupby() and count() to calculate the number of employees in each department
employee_count = df.groupby("Department")["Name"].count().reset_index(name="Employee Count")

print("Number of employees in each department:")
employee_count

Number of employees in each department:

  Department  Employee Count
0    Finance               2
1         HR               3
2         IT               2